// Generated by CoffeeScript 1.6.3
(function() {
	document.addEventListener('DOMContentLoaded', function() {
		var demos, logo, methods;
		if (!OriDomi.isSupported) {
			document.getElementById('unsupported').style.display = 'block';
			return;
		}
		demo = new OriDomi('.origami', {
			hPanels: 5,
			ripple: true
		});
		setTimeout(function() {
			demo.reveal(30, 'bottom');
		}, 1000);

	});

}).call(this);